// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: AssetSymbols.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ticker struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker   string  `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Price    float32 `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency string  `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AssetSymbols_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_AssetSymbols_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_AssetSymbols_proto_rawDescGZIP(), []int{0}
}

func (x *Ticker) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Ticker) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Ticker) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetAssetSymbolTickerPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker string `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *GetAssetSymbolTickerPriceRequest) Reset() {
	*x = GetAssetSymbolTickerPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AssetSymbols_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetSymbolTickerPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetSymbolTickerPriceRequest) ProtoMessage() {}

func (x *GetAssetSymbolTickerPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AssetSymbols_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetSymbolTickerPriceRequest.ProtoReflect.Descriptor instead.
func (*GetAssetSymbolTickerPriceRequest) Descriptor() ([]byte, []int) {
	return file_AssetSymbols_proto_rawDescGZIP(), []int{1}
}

func (x *GetAssetSymbolTickerPriceRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

type GetAssetSymbolTickerPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker *Ticker `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
}

func (x *GetAssetSymbolTickerPriceResponse) Reset() {
	*x = GetAssetSymbolTickerPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_AssetSymbols_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAssetSymbolTickerPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetSymbolTickerPriceResponse) ProtoMessage() {}

func (x *GetAssetSymbolTickerPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_AssetSymbols_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetSymbolTickerPriceResponse.ProtoReflect.Descriptor instead.
func (*GetAssetSymbolTickerPriceResponse) Descriptor() ([]byte, []int) {
	return file_AssetSymbols_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssetSymbolTickerPriceResponse) GetTicker() *Ticker {
	if x != nil {
		return x.Ticker
	}
	return nil
}

var File_AssetSymbols_proto protoreflect.FileDescriptor

var file_AssetSymbols_proto_rawDesc = []byte{
	0x0a, 0x12, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x52, 0x0a, 0x06, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x22, 0x3a, 0x0a,
	0x20, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x54,
	0x69, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x48, 0x0a, 0x21, 0x47, 0x65, 0x74,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x06, 0x74, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x32, 0x7c, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x73, 0x12, 0x6c, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x25, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x73, 0x73, 0x65, 0x74, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x72, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x65, 0x76, 0x69, 0x6c, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x73,
	0x6e, 0x69, 0x74, 0x63, 0x68, 0x2f, 0x64, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x2f, 0x75, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_AssetSymbols_proto_rawDescOnce sync.Once
	file_AssetSymbols_proto_rawDescData = file_AssetSymbols_proto_rawDesc
)

func file_AssetSymbols_proto_rawDescGZIP() []byte {
	file_AssetSymbols_proto_rawDescOnce.Do(func() {
		file_AssetSymbols_proto_rawDescData = protoimpl.X.CompressGZIP(file_AssetSymbols_proto_rawDescData)
	})
	return file_AssetSymbols_proto_rawDescData
}

var file_AssetSymbols_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AssetSymbols_proto_goTypes = []interface{}{
	(*Ticker)(nil),                            // 0: rpc.Ticker
	(*GetAssetSymbolTickerPriceRequest)(nil),  // 1: rpc.GetAssetSymbolTickerPriceRequest
	(*GetAssetSymbolTickerPriceResponse)(nil), // 2: rpc.GetAssetSymbolTickerPriceResponse
}
var file_AssetSymbols_proto_depIdxs = []int32{
	0, // 0: rpc.GetAssetSymbolTickerPriceResponse.ticker:type_name -> rpc.Ticker
	1, // 1: rpc.AssetSymbols.GetAssetSymbolTickerPrice:input_type -> rpc.GetAssetSymbolTickerPriceRequest
	2, // 2: rpc.AssetSymbols.GetAssetSymbolTickerPrice:output_type -> rpc.GetAssetSymbolTickerPriceResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_AssetSymbols_proto_init() }
func file_AssetSymbols_proto_init() {
	if File_AssetSymbols_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_AssetSymbols_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ticker); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AssetSymbols_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetSymbolTickerPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_AssetSymbols_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAssetSymbolTickerPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_AssetSymbols_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_AssetSymbols_proto_goTypes,
		DependencyIndexes: file_AssetSymbols_proto_depIdxs,
		MessageInfos:      file_AssetSymbols_proto_msgTypes,
	}.Build()
	File_AssetSymbols_proto = out.File
	file_AssetSymbols_proto_rawDesc = nil
	file_AssetSymbols_proto_goTypes = nil
	file_AssetSymbols_proto_depIdxs = nil
}
